import Head from 'next/head';
import { useQuery } from 'urql';
import { PRODUCT_QUERY } from '../lib/query';
import { ProductCard } from '@/components/ProductCard';
import { Gallery } from '@/styles/Gallery';

export default function Home() {
  const [results] = useQuery({ query: PRODUCT_QUERY });

  const { data, error, fetching } = results;

  if (fetching) {
    return <p>data is loading</p>;
  }

  if (error) {
    return <p>{error.message}</p>;
  }

  const products = data.products.data;
  return (
    <>
      <Head>
        <title>Home page</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Gallery>
          {products.map((product) => {
            return (
              <ProductCard
                key={product.attributes.slug}
                productData={product.attributes}
              />
            );
          })}
        </Gallery>
      </main>
    </>
  );
}
